Moodle Full

diff --git a/bin/moodle-docker-compose b/bin/moodle-docker-compose
--- a/bin/moodle-docker-compose
+++ b/bin/moodle-docker-compose
@@ -13,6 +13,12 @@ then
     exit 1
 fi
 
+if [ -z "$MOODLE_DOCKER_DB_WP" ];
+then
+    echo 'Error: $MOODLE_DOCKER_DB_WP is not set'
+    exit 1
+fi
+
 # Nasty portable way to the directory of this script, following symlink,
 # because readlink -f not on OSX. Thanks stack overflow..
 SOURCE="${BASH_SOURCE[0]}"
@@ -147,7 +153,9 @@ fi
 # Mac OS Compatbility
 if [[ "$(uname)" == "Darwin" ]]; then
     # Support https://docs.docker.com/docker-for-mac/osxfs-caching/
-    dockercompose="${dockercompose} -f ${basedir}/volumes-cached.yml"
+    #dockercompose="${dockercompose} -f ${basedir}/volumes-cached.yml"
+    # https://vivait.co.uk/labs/docker-for-mac-performance-using-nfs
+    dockercompose="${dockercompose} -f ${basedir}/volumes-nfs.yml"
 fi
 
 
